spring:

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:mothertest;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
   
  jpa:
     hibernate:
       ddl-auto: create-drop